### ISSUE TITLE
Move Tinkerbell web site over to Netlify + Hugo

### ISSUE THREAD

**Issue by vielmetti** [tinkerbell/tinkerbell.github.io#2]
The next version of the web site will be done with [Hugo](https://gohugo.io/) and [Netlify](https://www.netlify.com/) - track that progress here.

**Comment by jacobsmith928** [comment]
@ronggur is working with @felixwidjaja on implementing a new design with TBD Jamstack platform.

**Comment by gauravgahlot** [comment]
Ohh. @jacobsmith928 I was about to send a PR, shall I hold on to it then?

**Comment by jacobsmith928** [comment]
@gauravgahlot I would just hold back. Sorry for the confusion!
